### ISSUE TITLE
Cloning project with `wrangler generate`

### ISSUE THREAD

**Issue by ranbel** [cloudflare/workers-access-external-auth-example#5]
Step 1 in https://developers.cloudflare.com/cloudflare-one/policies/access/external-evaluation/#1-create-a-new-worker gives the following error:

🔧   Creating project called `my-worker-1`...
Error: ⛔   Git Error: failed to find branch `master`                                                                                        
Error: tried running command:
/Users/ranbel/Library/Caches/.wrangler/cargo-generate-0.5.0/cargo-generate generate --git https://github.com/cloudflare/workers-access-external-auth-example --name my-worker-1 --force
exited with exit status: 1

Wondering if the main branch should be renamed to `master` or if there's a better wrangler command to use?

**Comment by jroyal** [comment]
Which version of wrangler are you using? I'm on `wrangler 2.6.2` and the command worked as expected. Maybe just need to update?

**Comment by ranbel** [comment]
That's probably the reason. I'm still on wrangler 1 due to some technical issues updating to wrangler 2.
